# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\"\x81\x04\n\x0e\x43osimaMsgGroup\x12&\n\x03msg\x18\x0f \x03(\x0b\x32\x19.CosimaMsgGroup.CosimaMsg\x12\x1b\n\x13\x63urrent_mosaik_step\x18\x10 \x01(\x05\x1a\xa9\x03\n\tCosimaMsg\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.CosimaMsgGroup.CosimaMsg.MsgType\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x13\n\x0bmax_advance\x18\x04 \x01(\x05\x12\x0c\n\x04size\x18\x05 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\x12\r\n\x05\x64\x65lay\x18\x07 \x01(\x01\x12\x0f\n\x07simTime\x18\x08 \x01(\x05\x12\x10\n\x08stepSize\x18\t \x01(\x05\x12\r\n\x05msgId\x18\n \x01(\t\x12\r\n\x05until\x18\x0b \x01(\x05\x12\x15\n\rcreation_time\x18\x0c \x01(\x05\x12\x15\n\rchange_module\x18\r \x01(\t\x12$\n\x1c\x63onnection_change_successful\x18\x0e \x01(\x08\"q\n\x07MsgType\x12\x07\n\x03\x43MD\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x0f\n\x0bMAX_ADVANCE\x10\x02\x12\x0b\n\x07WAITING\x10\x03\x12\x16\n\x12TRANSMISSION_ERROR\x10\x04\x12\x0e\n\nDISCONNECT\x10\x05\x12\r\n\tRECONNECT\x10\x06\x62\x06proto3')
)



_COSIMAMSGGROUP_COSIMAMSG_MSGTYPE = _descriptor.EnumDescriptor(
  name='MsgType',
  full_name='CosimaMsgGroup.CosimaMsg.MsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX_ADVANCE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WAITING', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSMISSION_ERROR', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECONNECT', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=418,
  serialized_end=531,
)
_sym_db.RegisterEnumDescriptor(_COSIMAMSGGROUP_COSIMAMSG_MSGTYPE)


_COSIMAMSGGROUP_COSIMAMSG = _descriptor.Descriptor(
  name='CosimaMsg',
  full_name='CosimaMsgGroup.CosimaMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='CosimaMsgGroup.CosimaMsg.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='CosimaMsgGroup.CosimaMsg.sender', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='CosimaMsgGroup.CosimaMsg.receiver', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_advance', full_name='CosimaMsgGroup.CosimaMsg.max_advance', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='CosimaMsgGroup.CosimaMsg.size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='CosimaMsgGroup.CosimaMsg.content', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delay', full_name='CosimaMsgGroup.CosimaMsg.delay', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simTime', full_name='CosimaMsgGroup.CosimaMsg.simTime', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stepSize', full_name='CosimaMsgGroup.CosimaMsg.stepSize', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgId', full_name='CosimaMsgGroup.CosimaMsg.msgId', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='until', full_name='CosimaMsgGroup.CosimaMsg.until', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='CosimaMsgGroup.CosimaMsg.creation_time', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='change_module', full_name='CosimaMsgGroup.CosimaMsg.change_module', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connection_change_successful', full_name='CosimaMsgGroup.CosimaMsg.connection_change_successful', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COSIMAMSGGROUP_COSIMAMSG_MSGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=531,
)

_COSIMAMSGGROUP = _descriptor.Descriptor(
  name='CosimaMsgGroup',
  full_name='CosimaMsgGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='CosimaMsgGroup.msg', index=0,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_mosaik_step', full_name='CosimaMsgGroup.current_mosaik_step', index=1,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COSIMAMSGGROUP_COSIMAMSG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=531,
)

_COSIMAMSGGROUP_COSIMAMSG.fields_by_name['type'].enum_type = _COSIMAMSGGROUP_COSIMAMSG_MSGTYPE
_COSIMAMSGGROUP_COSIMAMSG.containing_type = _COSIMAMSGGROUP
_COSIMAMSGGROUP_COSIMAMSG_MSGTYPE.containing_type = _COSIMAMSGGROUP_COSIMAMSG
_COSIMAMSGGROUP.fields_by_name['msg'].message_type = _COSIMAMSGGROUP_COSIMAMSG
DESCRIPTOR.message_types_by_name['CosimaMsgGroup'] = _COSIMAMSGGROUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CosimaMsgGroup = _reflection.GeneratedProtocolMessageType('CosimaMsgGroup', (_message.Message,), dict(

  CosimaMsg = _reflection.GeneratedProtocolMessageType('CosimaMsg', (_message.Message,), dict(
    DESCRIPTOR = _COSIMAMSGGROUP_COSIMAMSG,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:CosimaMsgGroup.CosimaMsg)
    ))
  ,
  DESCRIPTOR = _COSIMAMSGGROUP,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:CosimaMsgGroup)
  ))
_sym_db.RegisterMessage(CosimaMsgGroup)
_sym_db.RegisterMessage(CosimaMsgGroup.CosimaMsg)


# @@protoc_insertion_point(module_scope)
