//
// Generated file, do not edit! Created by nedtool 5.6 from messages/AttackType.msg.
//

#ifndef __ATTACKTYPE_M_H
#define __ATTACKTYPE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>messages/AttackType.msg:17</tt> by nedtool.
 * <pre>
 * enum AttackType
 * {
 *     PacketDrop = 0;
 *     PacketFalsification = 1;
 *     PacketDelay = 2;
 * }
 * </pre>
 */
enum AttackType {
    PacketDrop = 0,
    PacketFalsification = 1,
    PacketDelay = 2
};

#endif // ifndef __ATTACKTYPE_M_H

