//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/AttackType.msg.
//

#ifndef __ATTACKTYPE_M_H
#define __ATTACKTYPE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

/**
 * Enum generated from <tt>messages/AttackType.msg:17</tt> by opp_msgtool.
 * <pre>
 * enum AttackType
 * {
 *     PacketDrop = 0;
 *     PacketFalsification = 1;
 *     PacketDelay = 2;
 * }
 * </pre>
 */
enum AttackType {
    PacketDrop = 0,
    PacketFalsification = 1,
    PacketDelay = 2
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AttackType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AttackType& e) { int n; b->unpack(n); e = static_cast<AttackType>(n); }


namespace omnetpp {


}  // namespace omnetpp

#endif // ifndef __ATTACKTYPE_M_H

