//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/ControlType.msg.
//

#ifndef __CONTROLTYPE_M_H
#define __CONTROLTYPE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

/**
 * Enum generated from <tt>messages/ControlType.msg:17</tt> by opp_msgtool.
 * <pre>
 * enum ControlType
 * {
 *     None = -1; // mode is undefined
 *     MaxAdvance = 0;
 *     EndOfStep = 1;
 *     Until = 2;
 *     Disconnect = 3;
 *     Reconnect = 4;
 *     ContinueWaiting = 5;
 *     Traffic = 6;
 * }
 * </pre>
 */
enum ControlType {
    None = -1,
    MaxAdvance = 0,
    EndOfStep = 1,
    Until = 2,
    Disconnect = 3,
    Reconnect = 4,
    ContinueWaiting = 5,
    Traffic = 6
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ControlType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ControlType& e) { int n; b->unpack(n); e = static_cast<ControlType>(n); }


namespace omnetpp {


}  // namespace omnetpp

#endif // ifndef __CONTROLTYPE_M_H

