//
// Generated file, do not edit! Created by nedtool 5.6 from messages/ControlType.msg.
//

#ifndef __CONTROLTYPE_M_H
#define __CONTROLTYPE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>messages/ControlType.msg:17</tt> by nedtool.
 * <pre>
 * enum ControlType
 * {
 *     None = -1; // mode is undefined
 *     MaxAdvance = 0;
 *     EndOfStep = 1;
 *     Until = 2;
 *     Disconnect = 3;
 *     Reconnect = 4;
 *     ContinueWaiting = 5;
 *     Traffic = 6;
 * }
 * </pre>
 */
enum ControlType {
    None = -1,
    MaxAdvance = 0,
    EndOfStep = 1,
    Until = 2,
    Disconnect = 3,
    Reconnect = 4,
    ContinueWaiting = 5,
    Traffic = 6
};

#endif // ifndef __CONTROLTYPE_M_H

