//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/TimerType.msg.
//

#ifndef __TIMERTYPE_M_H
#define __TIMERTYPE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

/**
 * Enum generated from <tt>messages/TimerType.msg:17</tt> by opp_msgtool.
 * <pre>
 * enum TimerType
 * {
 *     NoType = -1; // mode is undefined
 *     Connect = 0;
 *     Send = 1;
 *     Close = 2;
 *     Renew = 3;
 *     ConnectTimeout = 4;
 * }
 * </pre>
 */
enum TimerType {
    NoType = -1,
    Connect = 0,
    Send = 1,
    Close = 2,
    Renew = 3,
    ConnectTimeout = 4
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TimerType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TimerType& e) { int n; b->unpack(n); e = static_cast<TimerType>(n); }


namespace omnetpp {


}  // namespace omnetpp

#endif // ifndef __TIMERTYPE_M_H

