//
// Generated file, do not edit! Created by nedtool 5.4 from ControlType.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CONTROLTYPE_M_H
#define __CONTROLTYPE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>ControlType.msg:17</tt> by nedtool.
 * <pre>
 * enum ControlType
 * {
 *     None = -1; // mode is undefined
 *     MaxAdvance = 0;
 * }
 * </pre>
 */
enum ControlType {
    None = -1,
    MaxAdvance = 0
};

#endif // ifndef __CONTROLTYPE_M_H

