// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_INCLUDED_message_2eproto
#define PROTOBUF_INCLUDED_message_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_message_2eproto 

namespace protobuf_message_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_message_2eproto
class CosimaMsgGroup;
class CosimaMsgGroupDefaultTypeInternal;
extern CosimaMsgGroupDefaultTypeInternal _CosimaMsgGroup_default_instance_;
class CosimaMsgGroup_CosimaMsg;
class CosimaMsgGroup_CosimaMsgDefaultTypeInternal;
extern CosimaMsgGroup_CosimaMsgDefaultTypeInternal _CosimaMsgGroup_CosimaMsg_default_instance_;
class TicTocMsg;
class TicTocMsgDefaultTypeInternal;
extern TicTocMsgDefaultTypeInternal _TicTocMsg_default_instance_;
namespace google {
namespace protobuf {
template<> ::CosimaMsgGroup* Arena::CreateMaybeMessage<::CosimaMsgGroup>(Arena*);
template<> ::CosimaMsgGroup_CosimaMsg* Arena::CreateMaybeMessage<::CosimaMsgGroup_CosimaMsg>(Arena*);
template<> ::TicTocMsg* Arena::CreateMaybeMessage<::TicTocMsg>(Arena*);
}  // namespace protobuf
}  // namespace google

enum CosimaMsgGroup_CosimaMsg_MsgType {
  CosimaMsgGroup_CosimaMsg_MsgType_CMD = 0,
  CosimaMsgGroup_CosimaMsg_MsgType_INFO = 1,
  CosimaMsgGroup_CosimaMsg_MsgType_MAX_ADVANCE = 2,
  CosimaMsgGroup_CosimaMsg_MsgType_WAITING = 3,
  CosimaMsgGroup_CosimaMsg_MsgType_CosimaMsgGroup_CosimaMsg_MsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  CosimaMsgGroup_CosimaMsg_MsgType_CosimaMsgGroup_CosimaMsg_MsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool CosimaMsgGroup_CosimaMsg_MsgType_IsValid(int value);
const CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg_MsgType_MsgType_MIN = CosimaMsgGroup_CosimaMsg_MsgType_CMD;
const CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg_MsgType_MsgType_MAX = CosimaMsgGroup_CosimaMsg_MsgType_WAITING;
const int CosimaMsgGroup_CosimaMsg_MsgType_MsgType_ARRAYSIZE = CosimaMsgGroup_CosimaMsg_MsgType_MsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* CosimaMsgGroup_CosimaMsg_MsgType_descriptor();
inline const ::std::string& CosimaMsgGroup_CosimaMsg_MsgType_Name(CosimaMsgGroup_CosimaMsg_MsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    CosimaMsgGroup_CosimaMsg_MsgType_descriptor(), value);
}
inline bool CosimaMsgGroup_CosimaMsg_MsgType_Parse(
    const ::std::string& name, CosimaMsgGroup_CosimaMsg_MsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CosimaMsgGroup_CosimaMsg_MsgType>(
    CosimaMsgGroup_CosimaMsg_MsgType_descriptor(), name, value);
}
// ===================================================================

class CosimaMsgGroup_CosimaMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CosimaMsgGroup.CosimaMsg) */ {
 public:
  CosimaMsgGroup_CosimaMsg();
  virtual ~CosimaMsgGroup_CosimaMsg();

  CosimaMsgGroup_CosimaMsg(const CosimaMsgGroup_CosimaMsg& from);

  inline CosimaMsgGroup_CosimaMsg& operator=(const CosimaMsgGroup_CosimaMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CosimaMsgGroup_CosimaMsg(CosimaMsgGroup_CosimaMsg&& from) noexcept
    : CosimaMsgGroup_CosimaMsg() {
    *this = ::std::move(from);
  }

  inline CosimaMsgGroup_CosimaMsg& operator=(CosimaMsgGroup_CosimaMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CosimaMsgGroup_CosimaMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CosimaMsgGroup_CosimaMsg* internal_default_instance() {
    return reinterpret_cast<const CosimaMsgGroup_CosimaMsg*>(
               &_CosimaMsgGroup_CosimaMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CosimaMsgGroup_CosimaMsg* other);
  friend void swap(CosimaMsgGroup_CosimaMsg& a, CosimaMsgGroup_CosimaMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CosimaMsgGroup_CosimaMsg* New() const final {
    return CreateMaybeMessage<CosimaMsgGroup_CosimaMsg>(NULL);
  }

  CosimaMsgGroup_CosimaMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CosimaMsgGroup_CosimaMsg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CosimaMsgGroup_CosimaMsg& from);
  void MergeFrom(const CosimaMsgGroup_CosimaMsg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CosimaMsgGroup_CosimaMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef CosimaMsgGroup_CosimaMsg_MsgType MsgType;
  static const MsgType CMD =
    CosimaMsgGroup_CosimaMsg_MsgType_CMD;
  static const MsgType INFO =
    CosimaMsgGroup_CosimaMsg_MsgType_INFO;
  static const MsgType MAX_ADVANCE =
    CosimaMsgGroup_CosimaMsg_MsgType_MAX_ADVANCE;
  static const MsgType WAITING =
    CosimaMsgGroup_CosimaMsg_MsgType_WAITING;
  static inline bool MsgType_IsValid(int value) {
    return CosimaMsgGroup_CosimaMsg_MsgType_IsValid(value);
  }
  static const MsgType MsgType_MIN =
    CosimaMsgGroup_CosimaMsg_MsgType_MsgType_MIN;
  static const MsgType MsgType_MAX =
    CosimaMsgGroup_CosimaMsg_MsgType_MsgType_MAX;
  static const int MsgType_ARRAYSIZE =
    CosimaMsgGroup_CosimaMsg_MsgType_MsgType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MsgType_descriptor() {
    return CosimaMsgGroup_CosimaMsg_MsgType_descriptor();
  }
  static inline const ::std::string& MsgType_Name(MsgType value) {
    return CosimaMsgGroup_CosimaMsg_MsgType_Name(value);
  }
  static inline bool MsgType_Parse(const ::std::string& name,
      MsgType* value) {
    return CosimaMsgGroup_CosimaMsg_MsgType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string sender = 2;
  void clear_sender();
  static const int kSenderFieldNumber = 2;
  const ::std::string& sender() const;
  void set_sender(const ::std::string& value);
  #if LANG_CXX11
  void set_sender(::std::string&& value);
  #endif
  void set_sender(const char* value);
  void set_sender(const char* value, size_t size);
  ::std::string* mutable_sender();
  ::std::string* release_sender();
  void set_allocated_sender(::std::string* sender);

  // string receiver = 3;
  void clear_receiver();
  static const int kReceiverFieldNumber = 3;
  const ::std::string& receiver() const;
  void set_receiver(const ::std::string& value);
  #if LANG_CXX11
  void set_receiver(::std::string&& value);
  #endif
  void set_receiver(const char* value);
  void set_receiver(const char* value, size_t size);
  ::std::string* mutable_receiver();
  ::std::string* release_receiver();
  void set_allocated_receiver(::std::string* receiver);

  // string content = 6;
  void clear_content();
  static const int kContentFieldNumber = 6;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  #if LANG_CXX11
  void set_content(::std::string&& value);
  #endif
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // .CosimaMsgGroup.CosimaMsg.MsgType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::CosimaMsgGroup_CosimaMsg_MsgType type() const;
  void set_type(::CosimaMsgGroup_CosimaMsg_MsgType value);

  // int32 max_advance = 4;
  void clear_max_advance();
  static const int kMaxAdvanceFieldNumber = 4;
  ::google::protobuf::int32 max_advance() const;
  void set_max_advance(::google::protobuf::int32 value);

  // int32 size = 5;
  void clear_size();
  static const int kSizeFieldNumber = 5;
  ::google::protobuf::int32 size() const;
  void set_size(::google::protobuf::int32 value);

  // int32 simTime = 8;
  void clear_simtime();
  static const int kSimTimeFieldNumber = 8;
  ::google::protobuf::int32 simtime() const;
  void set_simtime(::google::protobuf::int32 value);

  // double delay = 7;
  void clear_delay();
  static const int kDelayFieldNumber = 7;
  double delay() const;
  void set_delay(double value);

  // int32 stepSize = 9;
  void clear_stepsize();
  static const int kStepSizeFieldNumber = 9;
  ::google::protobuf::int32 stepsize() const;
  void set_stepsize(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CosimaMsgGroup.CosimaMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr sender_;
  ::google::protobuf::internal::ArenaStringPtr receiver_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  int type_;
  ::google::protobuf::int32 max_advance_;
  ::google::protobuf::int32 size_;
  ::google::protobuf::int32 simtime_;
  double delay_;
  ::google::protobuf::int32 stepsize_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CosimaMsgGroup : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CosimaMsgGroup) */ {
 public:
  CosimaMsgGroup();
  virtual ~CosimaMsgGroup();

  CosimaMsgGroup(const CosimaMsgGroup& from);

  inline CosimaMsgGroup& operator=(const CosimaMsgGroup& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CosimaMsgGroup(CosimaMsgGroup&& from) noexcept
    : CosimaMsgGroup() {
    *this = ::std::move(from);
  }

  inline CosimaMsgGroup& operator=(CosimaMsgGroup&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CosimaMsgGroup& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CosimaMsgGroup* internal_default_instance() {
    return reinterpret_cast<const CosimaMsgGroup*>(
               &_CosimaMsgGroup_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CosimaMsgGroup* other);
  friend void swap(CosimaMsgGroup& a, CosimaMsgGroup& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CosimaMsgGroup* New() const final {
    return CreateMaybeMessage<CosimaMsgGroup>(NULL);
  }

  CosimaMsgGroup* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CosimaMsgGroup>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CosimaMsgGroup& from);
  void MergeFrom(const CosimaMsgGroup& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CosimaMsgGroup* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef CosimaMsgGroup_CosimaMsg CosimaMsg;

  // accessors -------------------------------------------------------

  // repeated .CosimaMsgGroup.CosimaMsg msg = 10;
  int msg_size() const;
  void clear_msg();
  static const int kMsgFieldNumber = 10;
  ::CosimaMsgGroup_CosimaMsg* mutable_msg(int index);
  ::google::protobuf::RepeatedPtrField< ::CosimaMsgGroup_CosimaMsg >*
      mutable_msg();
  const ::CosimaMsgGroup_CosimaMsg& msg(int index) const;
  ::CosimaMsgGroup_CosimaMsg* add_msg();
  const ::google::protobuf::RepeatedPtrField< ::CosimaMsgGroup_CosimaMsg >&
      msg() const;

  // @@protoc_insertion_point(class_scope:CosimaMsgGroup)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::CosimaMsgGroup_CosimaMsg > msg_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TicTocMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TicTocMsg) */ {
 public:
  TicTocMsg();
  virtual ~TicTocMsg();

  TicTocMsg(const TicTocMsg& from);

  inline TicTocMsg& operator=(const TicTocMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TicTocMsg(TicTocMsg&& from) noexcept
    : TicTocMsg() {
    *this = ::std::move(from);
  }

  inline TicTocMsg& operator=(TicTocMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TicTocMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TicTocMsg* internal_default_instance() {
    return reinterpret_cast<const TicTocMsg*>(
               &_TicTocMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(TicTocMsg* other);
  friend void swap(TicTocMsg& a, TicTocMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TicTocMsg* New() const final {
    return CreateMaybeMessage<TicTocMsg>(NULL);
  }

  TicTocMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TicTocMsg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TicTocMsg& from);
  void MergeFrom(const TicTocMsg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TicTocMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string content = 1;
  void clear_content();
  static const int kContentFieldNumber = 1;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  #if LANG_CXX11
  void set_content(::std::string&& value);
  #endif
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // @@protoc_insertion_point(class_scope:TicTocMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CosimaMsgGroup_CosimaMsg

// .CosimaMsgGroup.CosimaMsg.MsgType type = 1;
inline void CosimaMsgGroup_CosimaMsg::clear_type() {
  type_ = 0;
}
inline ::CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg::type() const {
  // @@protoc_insertion_point(field_get:CosimaMsgGroup.CosimaMsg.type)
  return static_cast< ::CosimaMsgGroup_CosimaMsg_MsgType >(type_);
}
inline void CosimaMsgGroup_CosimaMsg::set_type(::CosimaMsgGroup_CosimaMsg_MsgType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:CosimaMsgGroup.CosimaMsg.type)
}

// string sender = 2;
inline void CosimaMsgGroup_CosimaMsg::clear_sender() {
  sender_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CosimaMsgGroup_CosimaMsg::sender() const {
  // @@protoc_insertion_point(field_get:CosimaMsgGroup.CosimaMsg.sender)
  return sender_.GetNoArena();
}
inline void CosimaMsgGroup_CosimaMsg::set_sender(const ::std::string& value) {
  
  sender_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CosimaMsgGroup.CosimaMsg.sender)
}
#if LANG_CXX11
inline void CosimaMsgGroup_CosimaMsg::set_sender(::std::string&& value) {
  
  sender_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CosimaMsgGroup.CosimaMsg.sender)
}
#endif
inline void CosimaMsgGroup_CosimaMsg::set_sender(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sender_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CosimaMsgGroup.CosimaMsg.sender)
}
inline void CosimaMsgGroup_CosimaMsg::set_sender(const char* value, size_t size) {
  
  sender_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CosimaMsgGroup.CosimaMsg.sender)
}
inline ::std::string* CosimaMsgGroup_CosimaMsg::mutable_sender() {
  
  // @@protoc_insertion_point(field_mutable:CosimaMsgGroup.CosimaMsg.sender)
  return sender_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CosimaMsgGroup_CosimaMsg::release_sender() {
  // @@protoc_insertion_point(field_release:CosimaMsgGroup.CosimaMsg.sender)
  
  return sender_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CosimaMsgGroup_CosimaMsg::set_allocated_sender(::std::string* sender) {
  if (sender != NULL) {
    
  } else {
    
  }
  sender_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sender);
  // @@protoc_insertion_point(field_set_allocated:CosimaMsgGroup.CosimaMsg.sender)
}

// string receiver = 3;
inline void CosimaMsgGroup_CosimaMsg::clear_receiver() {
  receiver_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CosimaMsgGroup_CosimaMsg::receiver() const {
  // @@protoc_insertion_point(field_get:CosimaMsgGroup.CosimaMsg.receiver)
  return receiver_.GetNoArena();
}
inline void CosimaMsgGroup_CosimaMsg::set_receiver(const ::std::string& value) {
  
  receiver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CosimaMsgGroup.CosimaMsg.receiver)
}
#if LANG_CXX11
inline void CosimaMsgGroup_CosimaMsg::set_receiver(::std::string&& value) {
  
  receiver_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CosimaMsgGroup.CosimaMsg.receiver)
}
#endif
inline void CosimaMsgGroup_CosimaMsg::set_receiver(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  receiver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CosimaMsgGroup.CosimaMsg.receiver)
}
inline void CosimaMsgGroup_CosimaMsg::set_receiver(const char* value, size_t size) {
  
  receiver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CosimaMsgGroup.CosimaMsg.receiver)
}
inline ::std::string* CosimaMsgGroup_CosimaMsg::mutable_receiver() {
  
  // @@protoc_insertion_point(field_mutable:CosimaMsgGroup.CosimaMsg.receiver)
  return receiver_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CosimaMsgGroup_CosimaMsg::release_receiver() {
  // @@protoc_insertion_point(field_release:CosimaMsgGroup.CosimaMsg.receiver)
  
  return receiver_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CosimaMsgGroup_CosimaMsg::set_allocated_receiver(::std::string* receiver) {
  if (receiver != NULL) {
    
  } else {
    
  }
  receiver_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), receiver);
  // @@protoc_insertion_point(field_set_allocated:CosimaMsgGroup.CosimaMsg.receiver)
}

// int32 max_advance = 4;
inline void CosimaMsgGroup_CosimaMsg::clear_max_advance() {
  max_advance_ = 0;
}
inline ::google::protobuf::int32 CosimaMsgGroup_CosimaMsg::max_advance() const {
  // @@protoc_insertion_point(field_get:CosimaMsgGroup.CosimaMsg.max_advance)
  return max_advance_;
}
inline void CosimaMsgGroup_CosimaMsg::set_max_advance(::google::protobuf::int32 value) {
  
  max_advance_ = value;
  // @@protoc_insertion_point(field_set:CosimaMsgGroup.CosimaMsg.max_advance)
}

// int32 size = 5;
inline void CosimaMsgGroup_CosimaMsg::clear_size() {
  size_ = 0;
}
inline ::google::protobuf::int32 CosimaMsgGroup_CosimaMsg::size() const {
  // @@protoc_insertion_point(field_get:CosimaMsgGroup.CosimaMsg.size)
  return size_;
}
inline void CosimaMsgGroup_CosimaMsg::set_size(::google::protobuf::int32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:CosimaMsgGroup.CosimaMsg.size)
}

// string content = 6;
inline void CosimaMsgGroup_CosimaMsg::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CosimaMsgGroup_CosimaMsg::content() const {
  // @@protoc_insertion_point(field_get:CosimaMsgGroup.CosimaMsg.content)
  return content_.GetNoArena();
}
inline void CosimaMsgGroup_CosimaMsg::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CosimaMsgGroup.CosimaMsg.content)
}
#if LANG_CXX11
inline void CosimaMsgGroup_CosimaMsg::set_content(::std::string&& value) {
  
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CosimaMsgGroup.CosimaMsg.content)
}
#endif
inline void CosimaMsgGroup_CosimaMsg::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CosimaMsgGroup.CosimaMsg.content)
}
inline void CosimaMsgGroup_CosimaMsg::set_content(const char* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CosimaMsgGroup.CosimaMsg.content)
}
inline ::std::string* CosimaMsgGroup_CosimaMsg::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:CosimaMsgGroup.CosimaMsg.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CosimaMsgGroup_CosimaMsg::release_content() {
  // @@protoc_insertion_point(field_release:CosimaMsgGroup.CosimaMsg.content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CosimaMsgGroup_CosimaMsg::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:CosimaMsgGroup.CosimaMsg.content)
}

// double delay = 7;
inline void CosimaMsgGroup_CosimaMsg::clear_delay() {
  delay_ = 0;
}
inline double CosimaMsgGroup_CosimaMsg::delay() const {
  // @@protoc_insertion_point(field_get:CosimaMsgGroup.CosimaMsg.delay)
  return delay_;
}
inline void CosimaMsgGroup_CosimaMsg::set_delay(double value) {
  
  delay_ = value;
  // @@protoc_insertion_point(field_set:CosimaMsgGroup.CosimaMsg.delay)
}

// int32 simTime = 8;
inline void CosimaMsgGroup_CosimaMsg::clear_simtime() {
  simtime_ = 0;
}
inline ::google::protobuf::int32 CosimaMsgGroup_CosimaMsg::simtime() const {
  // @@protoc_insertion_point(field_get:CosimaMsgGroup.CosimaMsg.simTime)
  return simtime_;
}
inline void CosimaMsgGroup_CosimaMsg::set_simtime(::google::protobuf::int32 value) {
  
  simtime_ = value;
  // @@protoc_insertion_point(field_set:CosimaMsgGroup.CosimaMsg.simTime)
}

// int32 stepSize = 9;
inline void CosimaMsgGroup_CosimaMsg::clear_stepsize() {
  stepsize_ = 0;
}
inline ::google::protobuf::int32 CosimaMsgGroup_CosimaMsg::stepsize() const {
  // @@protoc_insertion_point(field_get:CosimaMsgGroup.CosimaMsg.stepSize)
  return stepsize_;
}
inline void CosimaMsgGroup_CosimaMsg::set_stepsize(::google::protobuf::int32 value) {
  
  stepsize_ = value;
  // @@protoc_insertion_point(field_set:CosimaMsgGroup.CosimaMsg.stepSize)
}

// -------------------------------------------------------------------

// CosimaMsgGroup

// repeated .CosimaMsgGroup.CosimaMsg msg = 10;
inline int CosimaMsgGroup::msg_size() const {
  return msg_.size();
}
inline void CosimaMsgGroup::clear_msg() {
  msg_.Clear();
}
inline ::CosimaMsgGroup_CosimaMsg* CosimaMsgGroup::mutable_msg(int index) {
  // @@protoc_insertion_point(field_mutable:CosimaMsgGroup.msg)
  return msg_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::CosimaMsgGroup_CosimaMsg >*
CosimaMsgGroup::mutable_msg() {
  // @@protoc_insertion_point(field_mutable_list:CosimaMsgGroup.msg)
  return &msg_;
}
inline const ::CosimaMsgGroup_CosimaMsg& CosimaMsgGroup::msg(int index) const {
  // @@protoc_insertion_point(field_get:CosimaMsgGroup.msg)
  return msg_.Get(index);
}
inline ::CosimaMsgGroup_CosimaMsg* CosimaMsgGroup::add_msg() {
  // @@protoc_insertion_point(field_add:CosimaMsgGroup.msg)
  return msg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CosimaMsgGroup_CosimaMsg >&
CosimaMsgGroup::msg() const {
  // @@protoc_insertion_point(field_list:CosimaMsgGroup.msg)
  return msg_;
}

// -------------------------------------------------------------------

// TicTocMsg

// string content = 1;
inline void TicTocMsg::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TicTocMsg::content() const {
  // @@protoc_insertion_point(field_get:TicTocMsg.content)
  return content_.GetNoArena();
}
inline void TicTocMsg::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TicTocMsg.content)
}
#if LANG_CXX11
inline void TicTocMsg::set_content(::std::string&& value) {
  
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TicTocMsg.content)
}
#endif
inline void TicTocMsg::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TicTocMsg.content)
}
inline void TicTocMsg::set_content(const char* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TicTocMsg.content)
}
inline ::std::string* TicTocMsg::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:TicTocMsg.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TicTocMsg::release_content() {
  // @@protoc_insertion_point(field_release:TicTocMsg.content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TicTocMsg::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:TicTocMsg.content)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::CosimaMsgGroup_CosimaMsg_MsgType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CosimaMsgGroup_CosimaMsg_MsgType>() {
  return ::CosimaMsgGroup_CosimaMsg_MsgType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_message_2eproto
