// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_message_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_message_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_CosimaMsgGroup_CosimaMsg;
}  // namespace protobuf_message_2eproto
class CosimaMsgGroup_CosimaMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CosimaMsgGroup_CosimaMsg>
      _instance;
} _CosimaMsgGroup_CosimaMsg_default_instance_;
class CosimaMsgGroupDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CosimaMsgGroup>
      _instance;
} _CosimaMsgGroup_default_instance_;
namespace protobuf_message_2eproto {
static void InitDefaultsCosimaMsgGroup_CosimaMsg() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CosimaMsgGroup_CosimaMsg_default_instance_;
    new (ptr) ::CosimaMsgGroup_CosimaMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CosimaMsgGroup_CosimaMsg::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CosimaMsgGroup_CosimaMsg =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCosimaMsgGroup_CosimaMsg}, {}};

static void InitDefaultsCosimaMsgGroup() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CosimaMsgGroup_default_instance_;
    new (ptr) ::CosimaMsgGroup();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CosimaMsgGroup::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_CosimaMsgGroup =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsCosimaMsgGroup}, {
      &protobuf_message_2eproto::scc_info_CosimaMsgGroup_CosimaMsg.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CosimaMsgGroup_CosimaMsg.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CosimaMsgGroup.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, sender_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, receiver_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, max_advance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, content_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, delay_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, simtime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, stepsize_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, msgid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, until_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, creation_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, change_module_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup_CosimaMsg, connection_change_successful_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup, msg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CosimaMsgGroup, current_mosaik_step_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::CosimaMsgGroup_CosimaMsg)},
  { 19, -1, sizeof(::CosimaMsgGroup)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CosimaMsgGroup_CosimaMsg_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CosimaMsgGroup_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "message.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rmessage.proto\"\201\004\n\016CosimaMsgGroup\022&\n\003ms"
      "g\030\017 \003(\0132\031.CosimaMsgGroup.CosimaMsg\022\033\n\023cu"
      "rrent_mosaik_step\030\020 \001(\005\032\251\003\n\tCosimaMsg\022/\n"
      "\004type\030\001 \001(\0162!.CosimaMsgGroup.CosimaMsg.M"
      "sgType\022\016\n\006sender\030\002 \001(\t\022\020\n\010receiver\030\003 \001(\t"
      "\022\023\n\013max_advance\030\004 \001(\005\022\014\n\004size\030\005 \001(\005\022\017\n\007c"
      "ontent\030\006 \001(\t\022\r\n\005delay\030\007 \001(\001\022\017\n\007simTime\030\010"
      " \001(\005\022\020\n\010stepSize\030\t \001(\005\022\r\n\005msgId\030\n \001(\t\022\r\n"
      "\005until\030\013 \001(\005\022\025\n\rcreation_time\030\014 \001(\005\022\025\n\rc"
      "hange_module\030\r \001(\t\022$\n\034connection_change_"
      "successful\030\016 \001(\010\"q\n\007MsgType\022\007\n\003CMD\020\000\022\010\n\004"
      "INFO\020\001\022\017\n\013MAX_ADVANCE\020\002\022\013\n\007WAITING\020\003\022\026\n\022"
      "TRANSMISSION_ERROR\020\004\022\016\n\nDISCONNECT\020\005\022\r\n\t"
      "RECONNECT\020\006b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 539);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "message.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_message_2eproto
const ::google::protobuf::EnumDescriptor* CosimaMsgGroup_CosimaMsg_MsgType_descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_enum_descriptors[0];
}
bool CosimaMsgGroup_CosimaMsg_MsgType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg::CMD;
const CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg::INFO;
const CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg::MAX_ADVANCE;
const CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg::WAITING;
const CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg::TRANSMISSION_ERROR;
const CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg::DISCONNECT;
const CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg::RECONNECT;
const CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg::MsgType_MIN;
const CosimaMsgGroup_CosimaMsg_MsgType CosimaMsgGroup_CosimaMsg::MsgType_MAX;
const int CosimaMsgGroup_CosimaMsg::MsgType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void CosimaMsgGroup_CosimaMsg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CosimaMsgGroup_CosimaMsg::kTypeFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kSenderFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kReceiverFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kMaxAdvanceFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kSizeFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kContentFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kDelayFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kSimTimeFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kStepSizeFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kMsgIdFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kUntilFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kCreationTimeFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kChangeModuleFieldNumber;
const int CosimaMsgGroup_CosimaMsg::kConnectionChangeSuccessfulFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CosimaMsgGroup_CosimaMsg::CosimaMsgGroup_CosimaMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_message_2eproto::scc_info_CosimaMsgGroup_CosimaMsg.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CosimaMsgGroup.CosimaMsg)
}
CosimaMsgGroup_CosimaMsg::CosimaMsgGroup_CosimaMsg(const CosimaMsgGroup_CosimaMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  sender_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.sender().size() > 0) {
    sender_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_);
  }
  receiver_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.receiver().size() > 0) {
    receiver_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.receiver_);
  }
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.content().size() > 0) {
    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  msgid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.msgid().size() > 0) {
    msgid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msgid_);
  }
  change_module_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.change_module().size() > 0) {
    change_module_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.change_module_);
  }
  ::memcpy(&type_, &from.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&connection_change_successful_) -
    reinterpret_cast<char*>(&type_)) + sizeof(connection_change_successful_));
  // @@protoc_insertion_point(copy_constructor:CosimaMsgGroup.CosimaMsg)
}

void CosimaMsgGroup_CosimaMsg::SharedCtor() {
  sender_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  receiver_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  change_module_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&connection_change_successful_) -
      reinterpret_cast<char*>(&type_)) + sizeof(connection_change_successful_));
}

CosimaMsgGroup_CosimaMsg::~CosimaMsgGroup_CosimaMsg() {
  // @@protoc_insertion_point(destructor:CosimaMsgGroup.CosimaMsg)
  SharedDtor();
}

void CosimaMsgGroup_CosimaMsg::SharedDtor() {
  sender_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  receiver_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  change_module_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CosimaMsgGroup_CosimaMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CosimaMsgGroup_CosimaMsg::descriptor() {
  ::protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CosimaMsgGroup_CosimaMsg& CosimaMsgGroup_CosimaMsg::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_message_2eproto::scc_info_CosimaMsgGroup_CosimaMsg.base);
  return *internal_default_instance();
}


void CosimaMsgGroup_CosimaMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:CosimaMsgGroup.CosimaMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sender_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  receiver_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  change_module_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&connection_change_successful_) -
      reinterpret_cast<char*>(&type_)) + sizeof(connection_change_successful_));
  _internal_metadata_.Clear();
}

bool CosimaMsgGroup_CosimaMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CosimaMsgGroup.CosimaMsg)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .CosimaMsgGroup.CosimaMsg.MsgType type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::CosimaMsgGroup_CosimaMsg_MsgType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string sender = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sender()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sender().data(), static_cast<int>(this->sender().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CosimaMsgGroup.CosimaMsg.sender"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string receiver = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_receiver()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->receiver().data(), static_cast<int>(this->receiver().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CosimaMsgGroup.CosimaMsg.receiver"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 max_advance = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &max_advance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 size = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string content = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->content().data(), static_cast<int>(this->content().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CosimaMsgGroup.CosimaMsg.content"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double delay = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(57u /* 57 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &delay_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 simTime = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &simtime_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 stepSize = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &stepsize_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string msgId = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msgid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msgid().data(), static_cast<int>(this->msgid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CosimaMsgGroup.CosimaMsg.msgId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 until = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(88u /* 88 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &until_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 creation_time = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(96u /* 96 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &creation_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string change_module = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u /* 106 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_change_module()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->change_module().data(), static_cast<int>(this->change_module().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CosimaMsgGroup.CosimaMsg.change_module"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool connection_change_successful = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(112u /* 112 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &connection_change_successful_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CosimaMsgGroup.CosimaMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CosimaMsgGroup.CosimaMsg)
  return false;
#undef DO_
}

void CosimaMsgGroup_CosimaMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CosimaMsgGroup.CosimaMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .CosimaMsgGroup.CosimaMsg.MsgType type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // string sender = 2;
  if (this->sender().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sender().data(), static_cast<int>(this->sender().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CosimaMsgGroup.CosimaMsg.sender");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->sender(), output);
  }

  // string receiver = 3;
  if (this->receiver().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->receiver().data(), static_cast<int>(this->receiver().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CosimaMsgGroup.CosimaMsg.receiver");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->receiver(), output);
  }

  // int32 max_advance = 4;
  if (this->max_advance() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->max_advance(), output);
  }

  // int32 size = 5;
  if (this->size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->size(), output);
  }

  // string content = 6;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CosimaMsgGroup.CosimaMsg.content");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->content(), output);
  }

  // double delay = 7;
  if (this->delay() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->delay(), output);
  }

  // int32 simTime = 8;
  if (this->simtime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->simtime(), output);
  }

  // int32 stepSize = 9;
  if (this->stepsize() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->stepsize(), output);
  }

  // string msgId = 10;
  if (this->msgid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msgid().data(), static_cast<int>(this->msgid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CosimaMsgGroup.CosimaMsg.msgId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->msgid(), output);
  }

  // int32 until = 11;
  if (this->until() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(11, this->until(), output);
  }

  // int32 creation_time = 12;
  if (this->creation_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(12, this->creation_time(), output);
  }

  // string change_module = 13;
  if (this->change_module().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->change_module().data(), static_cast<int>(this->change_module().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CosimaMsgGroup.CosimaMsg.change_module");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      13, this->change_module(), output);
  }

  // bool connection_change_successful = 14;
  if (this->connection_change_successful() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(14, this->connection_change_successful(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CosimaMsgGroup.CosimaMsg)
}

::google::protobuf::uint8* CosimaMsgGroup_CosimaMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CosimaMsgGroup.CosimaMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .CosimaMsgGroup.CosimaMsg.MsgType type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // string sender = 2;
  if (this->sender().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sender().data(), static_cast<int>(this->sender().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CosimaMsgGroup.CosimaMsg.sender");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->sender(), target);
  }

  // string receiver = 3;
  if (this->receiver().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->receiver().data(), static_cast<int>(this->receiver().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CosimaMsgGroup.CosimaMsg.receiver");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->receiver(), target);
  }

  // int32 max_advance = 4;
  if (this->max_advance() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->max_advance(), target);
  }

  // int32 size = 5;
  if (this->size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->size(), target);
  }

  // string content = 6;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CosimaMsgGroup.CosimaMsg.content");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->content(), target);
  }

  // double delay = 7;
  if (this->delay() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->delay(), target);
  }

  // int32 simTime = 8;
  if (this->simtime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->simtime(), target);
  }

  // int32 stepSize = 9;
  if (this->stepsize() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->stepsize(), target);
  }

  // string msgId = 10;
  if (this->msgid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msgid().data(), static_cast<int>(this->msgid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CosimaMsgGroup.CosimaMsg.msgId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->msgid(), target);
  }

  // int32 until = 11;
  if (this->until() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(11, this->until(), target);
  }

  // int32 creation_time = 12;
  if (this->creation_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(12, this->creation_time(), target);
  }

  // string change_module = 13;
  if (this->change_module().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->change_module().data(), static_cast<int>(this->change_module().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CosimaMsgGroup.CosimaMsg.change_module");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        13, this->change_module(), target);
  }

  // bool connection_change_successful = 14;
  if (this->connection_change_successful() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(14, this->connection_change_successful(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CosimaMsgGroup.CosimaMsg)
  return target;
}

size_t CosimaMsgGroup_CosimaMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CosimaMsgGroup.CosimaMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string sender = 2;
  if (this->sender().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sender());
  }

  // string receiver = 3;
  if (this->receiver().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->receiver());
  }

  // string content = 6;
  if (this->content().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());
  }

  // string msgId = 10;
  if (this->msgid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msgid());
  }

  // string change_module = 13;
  if (this->change_module().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->change_module());
  }

  // .CosimaMsgGroup.CosimaMsg.MsgType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // int32 max_advance = 4;
  if (this->max_advance() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->max_advance());
  }

  // int32 size = 5;
  if (this->size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->size());
  }

  // int32 simTime = 8;
  if (this->simtime() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->simtime());
  }

  // double delay = 7;
  if (this->delay() != 0) {
    total_size += 1 + 8;
  }

  // int32 stepSize = 9;
  if (this->stepsize() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->stepsize());
  }

  // int32 until = 11;
  if (this->until() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->until());
  }

  // int32 creation_time = 12;
  if (this->creation_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->creation_time());
  }

  // bool connection_change_successful = 14;
  if (this->connection_change_successful() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CosimaMsgGroup_CosimaMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CosimaMsgGroup.CosimaMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const CosimaMsgGroup_CosimaMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CosimaMsgGroup_CosimaMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CosimaMsgGroup.CosimaMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CosimaMsgGroup.CosimaMsg)
    MergeFrom(*source);
  }
}

void CosimaMsgGroup_CosimaMsg::MergeFrom(const CosimaMsgGroup_CosimaMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CosimaMsgGroup.CosimaMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sender().size() > 0) {

    sender_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_);
  }
  if (from.receiver().size() > 0) {

    receiver_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.receiver_);
  }
  if (from.content().size() > 0) {

    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  if (from.msgid().size() > 0) {

    msgid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msgid_);
  }
  if (from.change_module().size() > 0) {

    change_module_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.change_module_);
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.max_advance() != 0) {
    set_max_advance(from.max_advance());
  }
  if (from.size() != 0) {
    set_size(from.size());
  }
  if (from.simtime() != 0) {
    set_simtime(from.simtime());
  }
  if (from.delay() != 0) {
    set_delay(from.delay());
  }
  if (from.stepsize() != 0) {
    set_stepsize(from.stepsize());
  }
  if (from.until() != 0) {
    set_until(from.until());
  }
  if (from.creation_time() != 0) {
    set_creation_time(from.creation_time());
  }
  if (from.connection_change_successful() != 0) {
    set_connection_change_successful(from.connection_change_successful());
  }
}

void CosimaMsgGroup_CosimaMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CosimaMsgGroup.CosimaMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CosimaMsgGroup_CosimaMsg::CopyFrom(const CosimaMsgGroup_CosimaMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CosimaMsgGroup.CosimaMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CosimaMsgGroup_CosimaMsg::IsInitialized() const {
  return true;
}

void CosimaMsgGroup_CosimaMsg::Swap(CosimaMsgGroup_CosimaMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CosimaMsgGroup_CosimaMsg::InternalSwap(CosimaMsgGroup_CosimaMsg* other) {
  using std::swap;
  sender_.Swap(&other->sender_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  receiver_.Swap(&other->receiver_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  content_.Swap(&other->content_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  msgid_.Swap(&other->msgid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  change_module_.Swap(&other->change_module_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(type_, other->type_);
  swap(max_advance_, other->max_advance_);
  swap(size_, other->size_);
  swap(simtime_, other->simtime_);
  swap(delay_, other->delay_);
  swap(stepsize_, other->stepsize_);
  swap(until_, other->until_);
  swap(creation_time_, other->creation_time_);
  swap(connection_change_successful_, other->connection_change_successful_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CosimaMsgGroup_CosimaMsg::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CosimaMsgGroup::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CosimaMsgGroup::kMsgFieldNumber;
const int CosimaMsgGroup::kCurrentMosaikStepFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CosimaMsgGroup::CosimaMsgGroup()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_message_2eproto::scc_info_CosimaMsgGroup.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CosimaMsgGroup)
}
CosimaMsgGroup::CosimaMsgGroup(const CosimaMsgGroup& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      msg_(from.msg_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  current_mosaik_step_ = from.current_mosaik_step_;
  // @@protoc_insertion_point(copy_constructor:CosimaMsgGroup)
}

void CosimaMsgGroup::SharedCtor() {
  current_mosaik_step_ = 0;
}

CosimaMsgGroup::~CosimaMsgGroup() {
  // @@protoc_insertion_point(destructor:CosimaMsgGroup)
  SharedDtor();
}

void CosimaMsgGroup::SharedDtor() {
}

void CosimaMsgGroup::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CosimaMsgGroup::descriptor() {
  ::protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CosimaMsgGroup& CosimaMsgGroup::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_message_2eproto::scc_info_CosimaMsgGroup.base);
  return *internal_default_instance();
}


void CosimaMsgGroup::Clear() {
// @@protoc_insertion_point(message_clear_start:CosimaMsgGroup)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msg_.Clear();
  current_mosaik_step_ = 0;
  _internal_metadata_.Clear();
}

bool CosimaMsgGroup::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CosimaMsgGroup)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .CosimaMsgGroup.CosimaMsg msg = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(122u /* 122 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_msg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 current_mosaik_step = 16;
      case 16: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(128u /* 128 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &current_mosaik_step_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CosimaMsgGroup)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CosimaMsgGroup)
  return false;
#undef DO_
}

void CosimaMsgGroup::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CosimaMsgGroup)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .CosimaMsgGroup.CosimaMsg msg = 15;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->msg_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      15,
      this->msg(static_cast<int>(i)),
      output);
  }

  // int32 current_mosaik_step = 16;
  if (this->current_mosaik_step() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(16, this->current_mosaik_step(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CosimaMsgGroup)
}

::google::protobuf::uint8* CosimaMsgGroup::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CosimaMsgGroup)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .CosimaMsgGroup.CosimaMsg msg = 15;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->msg_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        15, this->msg(static_cast<int>(i)), deterministic, target);
  }

  // int32 current_mosaik_step = 16;
  if (this->current_mosaik_step() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(16, this->current_mosaik_step(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CosimaMsgGroup)
  return target;
}

size_t CosimaMsgGroup::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CosimaMsgGroup)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .CosimaMsgGroup.CosimaMsg msg = 15;
  {
    unsigned int count = static_cast<unsigned int>(this->msg_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->msg(static_cast<int>(i)));
    }
  }

  // int32 current_mosaik_step = 16;
  if (this->current_mosaik_step() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->current_mosaik_step());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CosimaMsgGroup::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CosimaMsgGroup)
  GOOGLE_DCHECK_NE(&from, this);
  const CosimaMsgGroup* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CosimaMsgGroup>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CosimaMsgGroup)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CosimaMsgGroup)
    MergeFrom(*source);
  }
}

void CosimaMsgGroup::MergeFrom(const CosimaMsgGroup& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CosimaMsgGroup)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  msg_.MergeFrom(from.msg_);
  if (from.current_mosaik_step() != 0) {
    set_current_mosaik_step(from.current_mosaik_step());
  }
}

void CosimaMsgGroup::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CosimaMsgGroup)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CosimaMsgGroup::CopyFrom(const CosimaMsgGroup& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CosimaMsgGroup)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CosimaMsgGroup::IsInitialized() const {
  return true;
}

void CosimaMsgGroup::Swap(CosimaMsgGroup* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CosimaMsgGroup::InternalSwap(CosimaMsgGroup* other) {
  using std::swap;
  CastToBase(&msg_)->InternalSwap(CastToBase(&other->msg_));
  swap(current_mosaik_step_, other->current_mosaik_step_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CosimaMsgGroup::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CosimaMsgGroup_CosimaMsg* Arena::CreateMaybeMessage< ::CosimaMsgGroup_CosimaMsg >(Arena* arena) {
  return Arena::CreateInternal< ::CosimaMsgGroup_CosimaMsg >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CosimaMsgGroup* Arena::CreateMaybeMessage< ::CosimaMsgGroup >(Arena* arena) {
  return Arena::CreateInternal< ::CosimaMsgGroup >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
